### ISSUE TITLE
Potential script issue?

### ISSUE THREAD

**Issue by mikaelssen** [Terri00/vrc8ball#100]
Hey, Tried installing the Pool Table to a world with the newest VRCsdk, seems like either I do something wrong, or the new udonsharp is being a derp.

I just get 

Assets\VRCBilliardsCE\Scripts\PoolMenu.cs(50,20): System.Exception: 'PoolStateManager' does not contain a definition for 'UnlockTable'

Line 785 definition, seems fine inn the manager.
Yet exeption happens...
Prob due to new SDK.

Would be nice if it's just me being a derp.

**Comment by Terri00** [comment]
That file does not belong to my project.

**Comment by mikaelssen** [comment]
yep, i'm the derp here, sorry for that 🤦
