### ISSUE TITLE
Scores being displayed weirdly

### ISSUE THREAD

**Issue by SazumeNeox** [Terri00/vrc8ball#11]
![VRChat_1920x1080_2020-12-19_23-47-28 385](https://user-images.githubusercontent.com/76274435/102705598-68a27f80-4257-11eb-9998-9446584a3dbb.png)
![VRChat_1920x1080_2020-12-20_00-04-24 666](https://user-images.githubusercontent.com/76274435/102705599-693b1600-4257-11eb-9fd6-df84c025af63.png)

The first picture was the other player (Gordon) on the break. Displayed is the score not matching the color of balls that went in.
The second picture is the same instance happening again.

Not necessarily an issue, but just wanted to let you know that this happened.

**Comment by Terri00** [comment]
thanks, this definitely needs to be handled correctly. will add a new case for it
