### ISSUE TITLE
sugestions

### ISSUE THREAD

**Issue by charbander6** [Terri00/vrc8ball#14]
i like the world alot and use it as a nice hang out world a few things i think would be nice additions would be a mirror in the back open area a jukebox with music and possibly a second table

**Comment by Terri00** [comment]
I'm developing some more areas to the map currently, but still unsure on adding anything too performance heavy such as mirror/music player

**Comment by charbander6** [comment]
could you make it toggelable or posiable make an edited version of the world that has preformance heavy things

**Comment by dragonash2019** [comment]
Would love if you decided to share out the pool table and be able to re-skin it. I could use it in my bar world! Perfect fit lol
Although I know nothing about udon ;p

**Comment by Terri00** [comment]
yup, easy re-skinning this will be a thing when the stable prefab is uploaded. 

i guess it makes sense to leave it to other community members if they want to add other map features as they see fit to their own worlds once this happens

**Comment by dragonash2019** [comment]
> yup, easy re-skinning this will be a thing when the stable prefab is uploaded.
> 
> i guess it makes sense to leave it to other community members if they want to add other map features as they see fit to their own worlds once this happens

nice :) just a quick follow up question. If you make this a prefab, can it be dropped into a non-udon world and work?
