### ISSUE TITLE
Cube ball

### ISSUE THREAD

**Issue by JayDaBaum** [Terri00/vrc8ball#18]
The is times where I will try to hit the cube ball with the stick and it goes right through the ball and there is times where I will be able to hit the ball but the cube ball won’t collide with the other  Billard balls.

**Comment by Terri00** [comment]
thanks for the report, can you confirm the ball passing through eachother occured within the last 2 days? i attempted adding a temporary workaround recently.

the cue going through ball is a new one, desktop/pc?

**Comment by dragonash2019** [comment]
> thanks for the report, can you confirm the ball passing through eachother occured within the last 2 days? i attempted adding a temporary workaround recently.
> 
> the cue going through ball is a new one, desktop/pc?

I can attest to the balls passing through each other. As of this past Sat and Sun, the game will "break". The cue ball will not hit any of the other balls and only see the 8-ball as the last one. The score indicator on the side of the table shows all balls pocketed and whoever hits the 8-ball in next wins, even though the balls are still on the table.

The only time I have seen the cue go through the cue ball is when someone picked up a cue after a match was started. Looking at the code on the wall and also player list on the table, you can tell if this happened. Resetting the game fixes that. Not so much a glitch though as it looks more like user error.

**Comment by Terri00** [comment]
Cheers, I put up a more comprehensive attempt ( in #10 ) to patch the first one we'll see if that did the trick.  

and yeah, whoever held/holding the cue when the turn gets transferred takes the control. its unintentional and need to find a way to prevent other user from taking the cue.

**Comment by Terri00** [comment]
as of commit c63cdaf, people not playing the game can no longer break it
