### ISSUE TITLE
Suggestion - 2 man team?

### ISSUE THREAD

**Issue by dragonash2019** [Terri00/vrc8ball#22]
Would it be possible to have a team option?

2 players per team:
Rules of the break are the same.
Turns are as follows: (will just use team colors for simplicity)

**Orange Player 1**: Plays until foul
turn changed to Blue Player 1
**Blue Player 1**: Plays until foul
turn changed to Orange Player 2
**Orange Player 2**: Plays until foul
turn changed to Blue Player 2:
**Blue Player 2**: Plays until foul

repeat until game over.

**Comment by Terri00** [comment]
seeing if i can get this working currently ^^

**Comment by Terri00** [comment]
Live on v1.0.0:
- Players can join a 'team' up to two players per team, and the cue stick can be freely passed / used between them
- There are no hard rules on who gets to play which shot on the team but I figure this can be left to the people playing
