### ISSUE TITLE
Weird lag issue during start of game

### ISSUE THREAD

**Issue by zauberparacelsus** [Terri00/vrc8ball#23]
I am experiencing a weird lag issue with the game.  While the balls are in motion, I am getting severe lag.  However, once a ball goes into a hole and the player colors are determined, the lag issue goes away.

Quick additional note, this is on desktop.  I am running Windows 8.1 Pro (64bit), CPU is a AMD FX-8350, GPU is an nVidia GTX 1650 Super.

EDIT: I was incorrect.  The lag continues after player colors are set, but gets reduced over time.  I think the lag is just getting reduced by there being fewer balls in play.

**Comment by Terri00** [comment]
can't do much about that, sorry
