### ISSUE TITLE
Phasing through walls

### ISSUE THREAD

**Issue by FoxtonDelta** [Terri00/vrc8ball#30]
i found out that when walking directly into the employee of the month sign you go right through it and can walk to the other side where the code is shown, unsure if this is used to quickly check the code from behind the bar or an actual bug.

![VRChat_1920x1080_2021-01-09_00-11-24 399](https://user-images.githubusercontent.com/77184522/104083760-40cb8980-520f-11eb-80cb-756cb9eb3f0a.png)

![VRChat_1920x1080_2021-01-09_00-11-17 354](https://user-images.githubusercontent.com/77184522/104083767-4d4fe200-520f-11eb-9dfc-f147227f076b.png)

**Comment by Terri00** [comment]
Welcome to _The Passage_
