### ISSUE TITLE
prefab layers not saved?

### ISSUE THREAD

**Issue by JeremyDF93** [Terri00/vrc8ball#31]
I believe the prefab is missing the correct layer setting for certain objects causing players to collide with the balls and table_col when its toggled on. Changing the layer for those objects and their children to 17 (Walkthrough) seems to fix this.

**Comment by Terri00** [comment]
you are correct!! i forgot to mention this on the readme, thanks

**Comment by Terri00** [comment]
Added some instructions on how to set it up
