### ISSUE TITLE
New Game - De-Sync

### ISSUE THREAD

**Issue by dragonash2019** [Terri00/vrc8ball#33]
It's happened a few times in the new world update.

I think it may be related to resetting the game, but not entirely positive. Every now and then, when you start a new game, no one else in the room can see the menu change, choose teams, click play, etc. Only the person initially starting the game can.

You can even start the game alone and no one else will see the table update.

The only "fix" is to create a new instance of the world.

**Comment by Terri00** [comment]
i'll look into it, thanks

**Comment by Terri00** [comment]
Think i found the issue to do with the simulation locking network updates but not being able to complete itself.
made some adjustments hopefully it will sort it. leaving open for now
