### ISSUE TITLE
Ability to change Emission Colors per Team on Table

### ISSUE THREAD

**Issue by itsKatVR** [Terri00/vrc8ball#34]
Is there a current way, or method to add an easy color picker for teams. This can be done through Unity pre- world upload.
(Color Codes for   BLUE / ORANGE)

I've looked around, and attempted to match colors with the environment better, but they seem to revert once the game has started.

Thankyou for an amazing Prefab / World!

**Comment by Terri00** [comment]
The colours can be edited in `harry_t/us/ht8b.cs` program file by changing the constants starting at line 192
They are paired to the ball texture sets and are as follows:

id | ball texture name | colours | constants 
--|---|---|-----------------------------------
0 | tballs_HT | Blue / Orange | `k_tableColourBlue` `k_tableColourOrange` 
1 | tballs_HT_0 | Pink / Green | `k_tableColourPink` `k_tableColourGreen`
2 | tballs_UK | Red / Yellow | `k_tableColourRed` `k_tableColourYellow`
3 ( 9 ball only ) | tballs_US | White / Black | `k_tableColorWhite` `k_tableColourBlack`

For the table cloth colour, you should edit:
- `k_fabricColour_gray` ( 8 ball modes )
- `k_fabricColour_blue` ( 9 ball )
- And for future reference, 4 ball will be using `k_fabricColour_green`

Note that the table cloth colours needs to be edited in ht8b.cs, and ht8b_menu.cs

Hope this helps =)

**Comment by Reploidsham** [comment]
This is good and relevant and believe it should be a bit more easily accessible.
