### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by IWEZN** [Terri00/vrc8ball#35]
Hi, I made a chalk model that can place in the world. Some players may happy to use it.
[chalkh8.zip](https://github.com/Terri00/vrc8ball/files/5797114/chalkh8.zip)

Looking for snooker but I just saw #32 btw

**Comment by F74Vincent** [comment]
hey, just discovered your world with a friend and we thought that some music could be good, maybe some youtube player or something like this would be very good.
GG for your work :)
