### ISSUE TITLE
9 Ball Win Condition Bug

### ISSUE THREAD

**Issue by OkitaIsami** [Terri00/vrc8ball#37]
When playing 9 Ball I found that you are able to sink the 9 Ball at any time and have it count as a win if the current objective ball knocks it in. Not a big deal since people would want to play properly anyway but figured I'd post what I found since this can happen by accident as well.

**_Example:_** On my turn the ball to sink is the 4 but I bounce the 4 into the 9 and sink just the 9 ball. This counts as a win instead of a loss.

**_Edit:_** Noticed that this also happens on Any ball in 9 Ball in a similar way, so if you were to aim and hit the 3 ball but it doesn't go in and instead knocks the 7 ball in, you get another turn even though you sank the wrong ball.

**Comment by Terri00** [comment]
This is actually the standard rules of 9 ball
- Legal shot is hitting lowest number ball first
- Win is any time 9 goes in without fouling
- Balls can be scored out of order

**Comment by OkitaIsami** [comment]
Oh my bad then, I don't know much about 9 ball lol
Just seemed odd to be able to win the game at any time by pocketing the 9 off another ball. Thanks for clarification!

**Comment by RikRifster** [comment]
Yes, that is accurate with the rules!
