### ISSUE TITLE
Friction - Suggestion

### ISSUE THREAD

**Issue by dragonash2019** [Terri00/vrc8ball#39]
Yup, me again :)
My friends and I play your game every day, so don't get too annoyed with me for posting AGAIN :)

Anyway, if possible, are you able to add a very slight amount of friction to the table?
The balls tend to roll so much more than on a normal pool table and felt has a bit a drag to it, if you know what I mean.

**Comment by Terri00** [comment]
we will get this with the updates included with what im working on in #36 =)
