### ISSUE TITLE
Double tables? There are no instructions for multiple tables in same world.

### ISSUE THREAD

**Issue by MrDummyNL** [Terri00/vrc8ball#41]
Someone made new pool game world and put TWO tables there.
And there are already some bugs, like the ball selection will color both table balls at same time.
Cue sometimes not grabbable.

You should add warning it's not designed for two tables yet. If it's possible, then add extra information to avoid problems between tables. Like add extra layer or so.

That is all.

**Comment by Reploidsham** [comment]
Currently issue #9

**Comment by MrDummyNL** [comment]
I saw it, so not advised. You might add it in general page don't make multiple tables - in case no one read this forum part.

**Comment by Terri00** [comment]
Added note: https://github.com/Terri00/vrc8ball/blob/master/README.md#caveats
