### ISSUE TITLE
Reset doesn't work when players are selected (before game start)

### ISSUE THREAD

**Issue by MrDummyNL** [Terri00/vrc8ball#45]
I noticed the Game Reset doesn't work on players selection before game starts.
Only when game start, then reset will work.

Sometimes there is double name error, and we want reset it, but it's not possible.
I discovered it can only reset when game is started.

Might adjust it a bit so it can also work at players selection? (Direct after button New Game.)
Because there it's already locked on the owner, so only owner can reset it.

We tried it earlier and it doesn't work, looks game is bugged. But then we discover it only work after game start...
So yeah, it makes things less confusing.

**Comment by Terri00** [comment]
Good idea, thanks
