### ISSUE TITLE
Translating!

### ISSUE THREAD

**Issue by Terri00** [Terri00/vrc8ball#46]
Attempting to translate game rules / text into various languages is underway.

We currently have:
- English
- Korean
- German
- Norwegian
- Japanese
- Turkish
- Spanish
- Italian
- Chinese
- French

Any language is welcome

You will get a picture and credit in the main build for your efforts. Please message me (discord: harry_t#9579) if you are interested! =)

**Comment by IWEZN** [comment]
I can help for chinese and japanese
