### ISSUE TITLE
Audio missing?

### ISSUE THREAD

**Issue by Ub3rZ4cH** [Terri00/vrc8ball#48]
I have no sound when I use this / the tables actions. 
In Unity it also says "Missing (Audio Clip)" the sounds of the balls etc I assume are not included in the package for some reason?

**Comment by Terri00** [comment]
They are included in the package, not sure why it is not linked for you.

**Comment by Ub3rZ4cH** [comment]
I have tried just now to import again and its still missing sound? ht8b_audio folder is there, and the sounds work. How do I ensure they are being referenced?
