### ISSUE TITLE
Need assistance with white ball;

### ISSUE THREAD

**Issue by Ub3rZ4cH** [Terri00/vrc8ball#49]
Firstly thank you for making this available. 
Secondly I rotated the entire table (made sure its on 0.0Y) the whole thing works perfectly however I get this issue.
(Since I am very new to udon) I am not sure which value or object to rotate to correct this.

https://i.imgur.com/yGnS5if.png

PS. I assumed it was okay to take the table and put it into another world I have kept the credit to this github in the world.
If this is not okay I will of course not use it in such a way.

**Comment by Terri00** [comment]
Table currently cannot be rotated, will be fixed in a future release

And yes, this software is free. It can be used how you like, does not require credit.

**Comment by Ub3rZ4cH** [comment]
Ah okay, Well it works fine rotated, I have been testing it, its just the guide line, I tried to rotate the guide object but I am not sure I am even doing it right lol. And well I put the credit there anyway :)
