### ISSUE TITLE
Balls sometimes miss collision

### ISSUE THREAD

**Issue by dragonash2019** [Terri00/vrc8ball#52]
I'm not really sure if this is the game itself, or VRC being VRC.
A lot of the times, when a ball is it hard, it will phase through the target ball. Many of my pals have cursed when trying combo shots :)

Also at times, mostly on the break, I see balls merge into each other as well.

**Comment by Terri00** [comment]
Epsilon was too large for collision prediction, fixed in next build (cue ball)
Im thinking of moving this prediction to happen on every ball but not sure if it will take too much cpu time.

**Comment by Terri00** [comment]
Reopening since collision can have a static resolution at very low cost. This will fix the balls merging on break.

**Comment by Terri00** [comment]
Static collision resolution added in: https://github.com/Terri00/vrc8ball/commit/7243cf0581cd928489c2a0edc72adee545f36c6b

Balls will no longer be able to merge into one another
