### ISSUE TITLE
Hitting power - over 9000! :)

### ISSUE THREAD

**Issue by dragonash2019** [Terri00/vrc8ball#53]
Wanted to make it a separate post so we don't group a ton of things together.

At times, when trying to lightly tap the ball, we will absolutely destroy it! :)
We aren't sure if it's a VRC thing, the game itself, or our tracking.

Since it seems to happen to us roughly at the same time and we all have different VR setups (I'm on an index), we have kind of ruled out the headset thing.

**Comment by Terri00** [comment]
Forgot to divide by deltatime, fixed in next build
