### ISSUE TITLE
walkthrough wall

### ISSUE THREAD

**Issue by smiley0bird** [Terri00/vrc8ball#54]
Behind the picture theres just a wall that you can walk strait through, i'm not sure if its a bug or a future thing but you can see a road, with houses, like a street, thats like a four way. Please fix

**Comment by smiley0bird** [comment]
https://user-images.githubusercontent.com/72012252/105506588-820d7000-5cca-11eb-94f6-fb32c13acbea.mp4
theres a video of it, to show it

**Comment by Terri00** [comment]
As with #30, I welcome you to, _The Passage_
