### ISSUE TITLE
XML file not found

### ISSUE THREAD

**Issue by Kobrey** [Terri00/vrc8ball#56]
![image_2021-01-24_141947](https://user-images.githubusercontent.com/77939948/105643796-37693080-5e4f-11eb-83ed-54dd22598b24.png)
When clicking the prefab for the vrc8ball, it takes me to another window saying xml file not found

**Comment by ringothefly** [comment]
I have this same issue and was about to report it. Would be great to have this fixed as I want to use this in a new home world for myself.

**Comment by Terri00** [comment]
Fixed link
