### ISSUE TITLE
License Policy

### ISSUE THREAD

**Issue by ssolarsystem** [Terri00/vrc8ball#57]
I found out this repository has been under the CC BY-NC-ND 3.0 via twitter user KIBA(https://twitter.com/kjh030529)

BUT, forked repository https://github.com/Xiexe/VRCBilliards is still under the The Unlicense.

How about contacting Xieve to change the license to same CC license?

Thank you for your attention

Solarsystem

**Comment by Terri00** [comment]
the CC license only applies to artwork, I asked xiexe to update their repo, currently they are changing the copyright works.

**Comment by ssolarsystem** [comment]
Thank you for your comment :)
I will close the issue solved
