### ISSUE TITLE
1.5.3 - Winner/Loser names incorrect

### ISSUE THREAD

**Issue by dragonash2019** [Terri00/vrc8ball#58]
Looks like the problem got a bit more complicated.
From what we were able to determine:

- Winner see's their own name
- Loser see's losers name
- Other's see "unknown name"
- Some people who aren't even playing see their name

**Comment by Terri00** [comment]
Oh yup i'm an idiot, wrote the fix into the local player's function. Not the networked one.
Will upload soon =)

**Comment by Terri00** [comment]
Alright, added that and a couple more fixes for race conditions to 1.5.4, all my local players have the same name so it is a little hard to spot if its correct.

I will leave open for now in case anything else comes up related to this (seems theres a few oversights that need looking at)
