### ISSUE TITLE
Forgotten code at line 746 to disable for Quest side

### ISSUE THREAD

**Issue by MrDummyNL** [Terri00/vrc8ball#59]
In 1.5.4, i noticed error at line 746. 
Then i saw you forgot to add extra checks. This below at 746 will remove the error message.

	#if HT8B_DEBUGGER
	_frp( FRP_WARN + sn_packetid + " >> local: " + local_playerid + " Winner: " + sn_winnerid + FRP_END );
	#endif

Then i can continue with Quest side world...

**Comment by Terri00** [comment]
Thanks, included with 1.5.41
