### ISSUE TITLE
Potting oppositions ball doesn't end turn

### ISSUE THREAD

**Issue by niallVR** [Terri00/vrc8ball#6]
When playing last night we encountered an interesting issue. [Twitch Clip](https://clips.twitch.tv/SullenBreakableEndiveCoolCat)

Player 1 (Lovus) - Blue
Player 2 (Me) - Orange

Lovus hit their own ball, which then knocked one of mine into a pocket. However, after my ball went in they also pocketed one of their own balls. According to the rules of pool, [seen here](https://www.rulesofsport.com/sports/pool.html), this is a foul and should end their turn.

What I expect happened is when Lovus pocketed their ball, it cancelled out the foul given for pocketing my ball.

**Comment by Terri00** [comment]
Thanks, I will add this rule with the next update.
