### ISSUE TITLE
Remove full screen desktop gameplay

### ISSUE THREAD

**Issue by MrDummyNL** [Terri00/vrc8ball#62]
The earlier version has 3D view for desktop, but miss indeed bal hitpoint.

But full 2D view makes for desktop more easier to play, makes the battle desktop vs VR not fair.
I should remove full 2D view and make it normal 3D view, can use E-lock and move like in 2D view.
The ball hitpoint stays but as seperated small box for ball hit control.

Now it's not very fair play, imho.

Also, i saw desktop looking weirdly in the air. It just not feels right. It's not always visible what desktop is doing.

**Comment by Terri00** [comment]
Its VR vs Desktop, its never going to be fair. Leaving as it is.
