### ISSUE TITLE
Minor optimization request

### ISSUE THREAD

**Issue by advanced4** [Terri00/vrc8ball#63]
The top 2 largest objects in my world are

 11.9 mb	 Resources/unity_builtin_extra
 2.7 mb	     Assets/harry_t/ht8b_materials/tui_basis.psd

Despite Unity offering the option to use crunch compression on the PSD, it doesn't work. If its not too much of a hassle, could tui_basis.psd be converted to a PNG/JPG? That way it can easily be compressed (or have it compressed be default if there's no noticeable difference in quality)

I did this before and it worked fine, it's just a mild inconvenience to keep an eye on that for changes anytime there's a new version of the pool table released

**Comment by Terri00** [comment]
Yeah that sounds like a good idea. I've heard some issues with PSD's in the past so I will export them all in future builds.

Side note, I think regular DXT1 should be fine this texture. Since so many of the 4x4 blocks in it are identical, the ZIP compression when you upload the world should take the size down quite a lot.

**Comment by dragonash2019** [comment]
please keep the psd in the assets though as the layers make the ball colors easy to edit.

**Comment by advanced4** [comment]
it appears with the latest release (from yesterday), 2 of the top 3 largest files in my world are now from this package. A new file, ``ttable_d.tga`` is reporting 2.7MB along with the 2.7MB from the psd file. Almost 6MB is a lot to budget for 2 image files which could be crunched. Just updating my request to include this file as well if possible

**Comment by Terri00** [comment]
Eh, after some consideration I don't think it needs it. The ZIP upload compresses it enough. (my entire uploaded world is 6mb, including lightmaps, other models etc).
