### ISSUE TITLE
Side Pocket Edges / Angles

### ISSUE THREAD

**Issue by dragonash2019** [Terri00/vrc8ball#64]
We've come to notice a couple of things after the recent update.
**The colliders are much more accurate**, but the side pockets have a bit of a hiccup to them

The edges expand out further than the visual material edge and its noticed when the ball hits the corner perfectly.
In addition, when the ball does hit it, it gets a jerky, zig-zag-like motion.

In fact, when I hit a straight shot when a ball is right against the bumper, it will hit the corner instead of rolling by. Please see my crappy sketch :)
![InkedScreenshot 2021-02-14 163825_LI](https://user-images.githubusercontent.com/47508016/107890612-db427b00-6ee7-11eb-8684-12d40208d753.jpg)

Additionally, it seems like the angles of the side pockets are wider than normal and the ball pocket is a tad shallow.
Two things tend to happen due to this.

When aiming for the center of the angled pad from a spot on the table, instead of bouncing the ball into the pocket, the ball tends to bounce between both pads multiple times and never goes in. Typically, the angled pad would "lead" the ball in and even if it did bounce it straight, the pocket was covering most of it.

See my second bad image and also a screenshot of a pool tables I grabbed from youtube for comparison.

![Screenshot 2021-02-14 165359](https://user-images.githubusercontent.com/47508016/107890217-adf4cd80-6ee5-11eb-9c36-0f41bc3d7ba5.png)

![image](https://user-images.githubusercontent.com/47508016/107890372-b8fc2d80-6ee6-11eb-8b15-854b77f29335.png)

I will note that when looking at pool tables, there seem to be slight variations on cushion angles, but it also seems like the side pockets make up for it by sticking out more. So really, it might simply come down to making the side pockets stick out a bit more. What do you think?
![image](https://user-images.githubusercontent.com/47508016/107890417-07113100-6ee7-11eb-8819-32a43464275e.png)

**Comment by Terri00** [comment]
Yea, i'm not sure what the standard angle is or if there is one. Additionally USA seems to use sharp cornered ones, in the UK we have rounded edges.

Started copying some code from my game engine to finally get this running smoothly. Trying a slight mix between uk/us as usual ^^

**Comment by Terri00** [comment]
Uploaded this new and improved edge detection to 1.6.0. Seems to work pretty solidly

**Comment by dragonash2019** [comment]
Looks like the balls still take a 90 degree turn when hitting the angle. Typically, when hitting the angled cushion, it should "lead" the ball in, similar to the corner pockets.

I should try making a recording of it to show you. I need to fire up my old fraps.

**Comment by Terri00** [comment]
ah thanks for the video. lets make the angle on those pockets more steep then

**Comment by Terri00** [comment]
I think this is a good middle ground, and added some more checks to make sure it catches it correctly

![image](https://user-images.githubusercontent.com/15938911/108393748-df360c00-720b-11eb-8505-a25ae64e3a4a.png)

**Comment by dragonash2019** [comment]
angles seem to work now. 
tested multiple shots and cuts into the center pocket with positive results
tested a straight shot next to the bumper from one side of the table to the other and no protruding edges interfered with the ball
