### ISSUE TITLE
Question - Table Asset

### ISSUE THREAD

**Issue by dragonash2019** [Terri00/vrc8ball#66]
Just curious about the possibility and/or implications of being able to hot-swap the table and ball assets.
Would be awesome to be able to have a customized table for your world, especially since this has become so popular. I just don't know how feasible something like this is

**Comment by Terri00** [comment]
Oh for sure, Spookyghostboo made a bunch of very nice ones: https://booth.pm/en/items/2736546

If they have the same dimentions, all need to do is replace the meshes tabletop_normal/score, and tabletop_normal/4ball_fillers and it works the same

**Comment by dragonash2019** [comment]
I see, he made those specifically for the prefab.
I was thinking of something really unique, like this - https://www.artstation.com/artwork/l6Gxa
But it might be more of an issue since it's not set up the same and includes new balls

**Comment by Terri00** [comment]
Yea it would not work out of the box currently. However with the new table update that im doing, I will include some of the development tools I created to help set up the values quickly to accomodate any sizes.
