### ISSUE TITLE
1.6.1 - Shader update

### ISSUE THREAD

**Issue by dragonash2019** [Terri00/vrc8ball#69]
Not sure if this is intended, but the table fabric greatly affects the highlights of the table itself
![VRChat_1920x1080_2021-02-17_20-46-39 092](https://user-images.githubusercontent.com/47508016/108292261-bfe2a480-7161-11eb-8d7a-79476192f8bd.png)

When the fabric is gray, it's not as noticeable. But if it is red or blue, like in the picture, the whole table looks like that color
![VRChat_1920x1080_2021-02-17_20-46-31 558](https://user-images.githubusercontent.com/47508016/108292336-ea346200-7161-11eb-8f21-3d17fdea93ed.png)

**Comment by Traediras** [comment]
That's coming from the table's reflection probe. Probably wouldn't need to have the table itself affected by said probe (it could use a reflection probe from the environment instead) but definitely useful for the balls since the table cloth is generally dynamic.

**Comment by Terri00** [comment]
Yep Traediras is correct.

For the next version I've split the reflection probe into two different ones. 

One that renders with the table, and a low res static one for just the environment.

**Comment by dragonash2019** [comment]
1.6.2
seems to still be doing it. Not a major thing though

![VRChat_1920x1080_2021-02-20_15-50-37 036](https://user-images.githubusercontent.com/47508016/108608511-54811880-7395-11eb-94f1-994c91e714e0.png)

![VRChat_1920x1080_2021-02-20_16-00-44 143](https://user-images.githubusercontent.com/47508016/108608514-564adc00-7395-11eb-9aa6-a04b1e7a8af6.png)

**Comment by dragonash2019** [comment]
fixed
