### ISSUE TITLE
9 ball mode

### ISSUE THREAD

**Issue by ShadowKitty123** [Terri00/vrc8ball#7]
Really loving the map, Have had it as my home world now since I first started playing it, Not entirely sure where to post suggestions but a 9 ball gamemode could be fun, I've always found it to be the more intense style of pool.

**Comment by Terri00** [comment]
Thanks for the suggestion! I'll look at implementing this once a stable point is reached with the standard mode

**Comment by Terri00** [comment]
9 ball mode is done, just working on some visual stuff, then it will be online =)

**Comment by Terri00** [comment]
Live on v1.0.0:
- Players can chose to play the game in 9 ball mode
- Rules may be a little wonky
