### ISSUE TITLE
1.6.2 - Ball "staging" before gameplay - low priority

### ISSUE THREAD

**Issue by dragonash2019** [Terri00/vrc8ball#71]
Sick of me yet? lol

Not so much of an issue since it's more decorative than anything else.
I noticed that since 1.6.1, the staged balls seem to spawn inside of the bumper.

Y=0 for me and I don't *think* I messed with anything.

![VRChat_1920x1080_2021-02-20_15-50-46 610](https://user-images.githubusercontent.com/47508016/108608576-d113f700-7395-11eb-91c6-9123f570ab25.png)

**Comment by Terri00** [comment]
haha, oops. the table got a bit smaller.
and no of course not, i'm grateful you have submit these, its free QA for me ^^. ( added a thank you note to the readme a couple days ago actually )
