### ISSUE TITLE
Thoughts on custom shader for balls?

### ISSUE THREAD

**Issue by dragonash2019** [Terri00/vrc8ball#74]
Was thinking about using Poiyomi (the newest version with locks) to change the look of the balls.
Will this have any adverse effects on the game?

**Comment by Terri00** [comment]
The only requirement for a shader used on the balls is that they need to define `_MainTex` as the diffuse sampler.

Most shaders follow this standard and I'm pretty sure Poiyomi's shaders do to, so should work exactly as expected.

**Comment by Terri00** [comment]
Side note if your also targetting quest: the shader replacement script looks for Standard shader to switch it to a mobile diffuse one, make sure you set up the shader in there. (ht8b > Quest_stuff)
