### ISSUE TITLE
1.6.3 - Under/Over Power 9000 snuck back in

### ISSUE THREAD

**Issue by dragonash2019** [Terri00/vrc8ball#75]
looks like this somehow snuck back in, although not as frequent as it once was.

overview:
Sometimes gentle shots go full blast
Sometimes hard shots have no power

Like I said before, not nearly as frequent as it once was, but was definitely not in 1.6.2

**Comment by Terri00** [comment]
damn.. 🤔 i have no idea what causes it, except maybe a frame spike. cannot reproduce locally, but i will review the input code for mistakes tommorow.

**Comment by dragonash2019** [comment]
> damn.. 🤔 i have no idea what causes it, except maybe a frame spike. cannot reproduce locally, but i will review the input code for mistakes tommorow.

FYI, this was all "local" (basically, build and test from unity). So nothing was uploaded.
It did take some time for it to happen. I noticed it late into testing and thought it was a fluke, but decided to keep going. I happened to get "lucky" and it happened back to back roughly 15 minutes and a TON of shots later.

If there are any logs I can provide you, let me know.

**Comment by Terri00** [comment]
I have an idea what this is could be related to now, something changed within vrcsdk that changed in what order scripts executes. it broke something else before, but i imagine it causes timing issues with how the cues move at inconsistent framerates.

Added explicit timing flags in commit https://github.com/Terri00/vrc8ball/commit/a884ff3881a99a85241f93bbf0e70c309dab8557

Uploading a new version after some testing.

**Comment by Terri00** [comment]
Pushed to 1.6.4b (1.6.3 release is modified to include the changes)

**Comment by dragonash2019** [comment]
resolved
