### ISSUE TITLE
Move scored balls to a certain angle

### ISSUE THREAD

**Issue by Legoman99573** [Terri00/vrc8ball#76]
I was gonna ask this as using a custom pool table besides the prefab one will sometimes have the scored balls hanging out the side and was wondering on how to move it around, like inwards a bit as I don't see a way to do this currently.

**Comment by Terri00** [comment]
yea this should totally take its position from a gameobject, It's currently hard-coded at:
https://github.com/Terri00/vrc8ball/blob/250f34b104555058dbfb2d1c80a414ae35994556/ht8b.cs#L1262
and the Y position of the scored balls is defined by k_RACK_HEIGHT.

**Comment by Terri00** [comment]
next version will include a gameobject called `RACK_POSITION`. Scored balls will be placed here along its forward axis. Writing a wiki page on custom table setups currently.

**Comment by MrDummyNL** [comment]
And wiki for move reset button, reset message, more objects and help boards which are not in package 1.6.2. But like i said earlier, GROUP them in own gameobject groups is much easier for customizing. Now it's spread out over whole asset and that is not nice grouping. 
I am not kidding. This is also part of nicer and organizing build work!
