### ISSUE TITLE
Pool Ball Spin Issue

### ISSUE THREAD

**Issue by rets34** [Terri00/vrc8ball#77]
https://user-images.githubusercontent.com/29514536/110188410-3679d600-7de1-11eb-8b25-091b1a4ce06d.mp4

Attached is a GIF of what I'm having.
The balls will move/roll correctly on the table, but they spin opposite directions like they're on ice.
ht8b has it's own layer and physics options are set. Version 1.6.3.

**Comment by Terri00** [comment]
is the table rotated maybe?

**Comment by rets34** [comment]
It was! set rotation to 0,0,0 and fixed it. So there's no way to have it in another angle?

**Comment by Terri00** [comment]
Not at the moment no, needs some work to accommodate different angles. Its currently a low priority task for me, but one day!

**Comment by NiyahVE** [comment]
Just noticed that aswell, I guess it's time to rotate the entire world accordinaly then !

Thanks for the work tho, you're doing a good job :)

**Comment by Terri00** [comment]
Added some updates for this in current release:
https://github.com/Terri00/vrc8ball/releases/tag/1.6.3

I've only tested on desktop currently, this issue in particular is fixed but might contain other problems, leaving open in-case something is wrong in VR mode.
