### ISSUE TITLE
[Request] Update billiard balls to US 8-ball specification.

### ISSUE THREAD

**Issue by Traediras** [Terri00/vrc8ball#81]
Did a search around of what standard size the billiard balls should be, and according to the World Pool-Billiard Association, all balls should be 2¼in (57mm).

Sauce: https://web.archive.org/web/20130928165510/http://www.wpa-pool.com/web/WPA_Tournament_Table_Equipment_Specifications

**Comment by Terri00** [comment]
![Unity_1PzRWN2t92](https://user-images.githubusercontent.com/15938911/111563025-1954e800-878f-11eb-8fb9-8cbf458e7bbc.png)

5 is current (60mm), 6 is proposed change.

Since it takes a lot of time to correct the maths, I won't be changing it, but I can assure you every other value is to standard ^^
