### ISSUE TITLE
Question: Table_Refiner + other subsections

### ISSUE THREAD

**Issue by dragonash2019** [Terri00/vrc8ball#83]
So I noticed a few pieces of the prefab have started to be siloed off - for lack of a better term.
For instance, the Rack_Position is now manually adjustable as well as the score. This seems to be starting to go into the direction of custom tables.

The newest addition (tehcnically, came before rack position) is the table refiner.
It appears that it controls the tables collision points, which makes me believe we will be able to use any custom table soon.

Is that the case or am I over analyzing things?

**Comment by Terri00** [comment]
Yep you got it, these are all feeding into a system that allows easy interchange between different table setups.

Here's a new table model I've been working on to test it, and a look at latest the config panel.

![peNaE7EgRA](https://user-images.githubusercontent.com/15938911/111839611-f6434900-88f2-11eb-8ad5-a91433074f9b.png)

**Comment by dragonash2019** [comment]
Oh sweet! Also, yay! No more going into the script to assign (or create) specific colors for the fabric and queues! lol

**Comment by MrDummyNL** [comment]
I should make 2 tables because i moved the scoreboard part to room wall (better visible for everyone). Table with scoreboard area on it, and table without scoreboard, so only table itself. Also it looks more nice without scoreboard area!

**Comment by dragonash2019** [comment]
been uppdated
