### ISSUE TITLE
Desktop Camera Blackout

### ISSUE THREAD

**Issue by dbernecker12** [Terri00/vrc8ball#86]
I followed the instructions on the setup and the table works in vr but when Desktop users hit E to toggle the camera for the pool table the screen just goes black. I have reloaded the pool table multiply times and made sure all layers and camera settings are right but I'm still getting the black screen. I'm not sure what to do to fix it?

**Comment by Terri00** [comment]
I believe its something to do with occlusion culling, I've never been sure what caused it but I know some people have fixed it so I will ask around.

**Comment by Codel1417** [comment]
Disable occlusion on the camera, or move the camera until it shows up
you don't have to disable occlusion culling on the table itself

**Comment by Terri00** [comment]
Thanks @Codel1417! In the future I'll have it be disabled in the prefab by default.
