### ISSUE TITLE
Aim Guide Sometimes Does not show up in 1.8

### ISSUE THREAD

**Issue by DJZephin** [Terri00/vrc8ball#89]
I'll test in a flat light world, but we're observing the guide line not showing up. Maybe its a shader issue. I'll test in a flat lighting world and update this post.

**Comment by DJZephin** [comment]
This is happening on the glass table. I have moved the Y axis to zero to test. The result is the same. Seems the guide line is below the table and can be seen clipping out of the sides.

**Comment by Terri00** [comment]
Ah, this must be to do with the Render Queue then. I've set the shader to use a value above 3000 now, and seems the shader needs work to support different table sizes.

Thanks for reporting

**Comment by DJZephin** [comment]
Ok Its happening with the object ball id circle in 9ball. Should I make any adjustments for testing? I can do that myself for you if you want.

**Comment by Terri00** [comment]
I think I got all of the shaders fixed now. As well as an incorrect option with the glass table material. Uploading soon

**Comment by DJZephin** [comment]
Tested and verified. Very nice work.
