### ISSUE TITLE
Multiple pool tables

### ISSUE THREAD

**Issue by Terri00** [Terri00/vrc8ball#9]
After hanging about in public lobbies it seems like necessity to have at least 2 tables in the ht8b world

This will require patching any world space calculations to instead use localspace.

To keep performance up it will be limited to 1 visible per room, to prevent multiple sims running at the same time.

**Comment by Terri00** [comment]
too much data sync to add currently.

**Comment by MrDummyNL** [comment]
The idea is make separated rooms, so if you enter another room, table can enabled automatically. So there will always one table active in your vision. No two tables (which some1 just tried it, but bugged too much).
