### ISSUE TITLE
something is not working

### ISSUE THREAD

**Issue by spyro12675** [Terri00/vrc8ball#92]
![image](https://user-images.githubusercontent.com/57742974/113813090-997cd500-97b2-11eb-8117-2ebc045e4ac0.png)
can someone help me nothing is working and the buttons just say YEET literally

**Comment by Codel1417** [comment]
Do you have sdk3-udon installed along with udonSharp

**Comment by spyro12675** [comment]
Yes i have udonsharp installed

**Comment by Terri00** [comment]
Need to apply config. This guide shows how to install: https://terri.tech/less.php?page=poolsetup

(the buttons will say yeet until the gane starts)

**Comment by dragonash2019** [comment]
also wanted to add, that ANY changes you make and want to keep need to be followed by apply config
