### ISSUE TITLE
[Question] why was documentation moved away from this repo?

### ISSUE THREAD

**Issue by Codel1417** [Terri00/vrc8ball#93]
What was the decision behind moving documentation to your website instead of here? The download page uses github for hosting files and the setup instructions don't have any enhancements on the new site.

**Comment by Terri00** [comment]
Easier to communicate things on a dedicated site, github is counter-intuitive for people unfamiliar with it and who do not need to see the source code. The custom table guide was the main reason for switching, needed that control there. 

My webserver has a 1 TB monthly transfer limit before i have to pay more so thats why downloads are uploaded to github.
