### ISSUE TITLE
Installation not working. Scripts issue

### ISSUE THREAD

**Issue by regandor87** [Terri00/vrc8ball#96]
I followed your guide on how to install to the letter, but i keep running in to script issues. 

https://forum.unity.com/threads/scripts-for-a-pooltable-udon-not-working-monobehaviour-issue.1101565/

I posted about it here hoping they would help, but i was told to ask you :)

**Comment by Terri00** [comment]
Hiya, looks like UdonSharp wasn't installed correctly.
Make sure you download and run the ***.unitypackage*** from this release or later: https://github.com/MerlinVR/UdonSharp/releases/tag/v0.19.8

**Comment by regandor87** [comment]
that worked! thanks ^^ maybe the one i downloaded got corrupted or something :)
